### ISSUE TITLE
scroll option with column resize

### ISSUE THREAD

**Issue by mmahmood2014** [dhobi/datatables.colResize#1]
Hi @dhobi, We have check your script but when we add a scrollbar in the grid, it stops working. it only allow to resize the header only. This is what we have done in javascript:

$(document).ready( function () {
var table = $('#example').DataTable({ "scrollX": true});

Do you have any suggestion on that?

**Comment by dhobi** [comment]
Hi

I'm successfuly using the plugin together with horizontal scrollable tables (scrollX). Possible that the plugin misses to detect this propery in your use case. I will check this asap.

**Comment by mmahmood2014** [comment]
Okay sure, I will look forward to hear from you.

**Comment by dhobi** [comment]
Can you retry it with the latest changes and let me know if it works better for you now?

**Comment by mmahmood2014** [comment]
Sure, Let me check

**Comment by dhobi** [comment]
Any update on this? I'll close the issue otherwise...
