### ISSUE TITLE
.enable(false) can't call internal fnDisable function

### ISSUE THREAD

**Issue by hchiam** [dhobi/datatables.colResize#14]
When calling `.enable(false)` I get this error: 

`Uncaught ReferenceError: fnDisable is not defined` 

![screenshot-of-production-bug](https://user-images.githubusercontent.com/18131787/179294088-df7d6e91-7b6f-437a-aa07-241f377fd0f1.png)

**Comment by dhobi** [comment]
Isn't this an issue with the colReorder plugin rather than colResize plugin?

**Comment by hchiam** [comment]
Oh you're right @dhobi! Whoops! I'll report this in [ColReorder](https://github.com/DataTables/ColReorder) instead
