### ISSUE TITLE
Issue with Chrome - Not working properly

### ISSUE THREAD

**Issue by 4wk-** [dhobi/datatables.colResize#3]
Hello,

It seems the livedemo is not working properly with Chrome.
```
Google Chrome is up to date
Version 91.0.4472.124 (Official Build) (64-bit)
```

Another user reported it a few month ago here:
https://datatables.net/forums/discussion/65799/datatable-column-resize-plugin

> ColReorderWithResize.js file seems to be having issues after chrome 91 update

Console is saying "resizing" then "I have been resized!" but nothing change on the DataTable.
Thanks!

**Comment by dhobi** [comment]
Hmm sorry about the late reply. The plugin should still work as of now. Could you try the updated live demo URL?
https://dhobi.github.io/datatables.colResize/
