### ISSUE TITLE
How to save/restore the width via Ajax?

### ISSUE THREAD

**Issue by gkieninger** [dhobi/datatables.colResize#4]
Hello!
I try to save and restore the width of each column. This is done by Ajax with a call to a Backend.
Saving seams to work for me, but I am not able to set the width of a column.
Maybe somebody can guide me? 
Thanks

**Comment by dhobi** [comment]
Have you found a solution to this already?

We are restoring the width of the colums after the datatable has initialized completely. We are using the initComplete callback here: https://datatables.net/reference/option/initComplete

**Comment by jstark518** [comment]
> Have you found a solution to this already?
> 
> We are restoring the width of the colums after the datatable has initialized completely. We are using the initComplete callback here: https://datatables.net/reference/option/initComplete

@dhobi would you be interested in a PR that has a saveState option that would store this in local storage like how datatables does for filters and sorting?

**Comment by dhobi** [comment]
@jstark518 You mean to do it like here https://datatables.net/reference/option/stateSave? I think that would be very nice!

**Comment by jstark518** [comment]
> @jstark518 You mean to do it like here https://datatables.net/reference/option/stateSave? I think that would be very nice!

Yup just like that.
